### ISSUE TITLE
Simple Control Panel

### ISSUE THREAD

**Issue by joebnich** [gibber-cc/gibber#33]
Hi Charlie,

I can not figure out how to get a dat.gui control panel to work with Gibber. I have attached a simple page that illustrates my problem. Can you take a look?

thanks,

Joe
[breaker.html.zip](https://github.com/charlieroberts/Gibber/files/162099/breaker.html.zip)

**Comment by joebnich** [comment]
sorry, that one was not working, here is one where the audio actually plays. 
[breaker.html 2.zip](https://github.com/charlieroberts/Gibber/files/162134/breaker.html.2.zip)

**Comment by charlieroberts** [comment]
cleaning up some old issues
