### ISSUE TITLE
Is gibber v2 up to date with the more recent performances ?

### ISSUE THREAD

**Issue by JTriggerFish** [gibber-cc/gibber#45]
Hi Charlie,
Seems like there hasn’t been much movement on the repo for a while but you’ve done some cool live performances a few months ago, does the repo have the latest code you were using ?

**Comment by charlieroberts** [comment]
Don't ask me why, but all the commits are in the audio repo. But I went ahead just now and put [the current playground online](https://charlieroberts.github.io/gibber.audio.lib/playground/).

But there's only one small demo, and no reference... although there's autocomplete / inline doc support for many objects. If you want to play with it anyways, feel free to ask questions in the [gibber channel at talk.lurk.org](https://chat.toplap.org/channel/gibber). A lot of it is of course very similar to gibber v1, but a lot of it is completely different (like the graphics engine).

Definitely pre-alpha software at the moment.

**Comment by JTriggerFish** [comment]
Thanks for all the work with getting this alpha release more stable Charlie !
