### ISSUE TITLE
package.json name

### ISSUE THREAD

**Issue by JTriggerFish** [gibber-cc/gibber#46]
The package.json file in the v2 branch looks weird:

{
  "name": "gibber.audio.lib",
  "version": "0.7.7",
  "description": "standalone audio library from Gibber to use in node or in HTML documents",
  "repository": {
    "type": "git",
    "url": "git://github.com/charlieroberts/gibber.audio.lib"
  },

Is this expected ? And if so what is the relationship with the separate gibber.audio.lib repo ?

Would you have some quick installation instructions for building and running locally assuming they differ from v1 ?

Many thanks !

**Comment by JTriggerFish** [comment]
To be clear I mean running the v2 server locally.

**Comment by charlieroberts** [comment]
cleaning up some old issues... not sure when this was fixed, but it's fixed now. There are also better build instructions in the main README.
