### ISSUE TITLE
Some commands don't work with French mac keyboard layout.

### ISSUE THREAD

**Issue by preidorg** [gibber-cc/gibber#51]
Hi there, 
I use a Mac with a French keyboard.  I cannot execute the ctrl+. command.

Accessing the . symbol requires pressing the shift key.  The other symbol on that key (the oe you get whenn you don't hold shift) is ; so we will call this the ;/. key.  Pressing the ctl key makes the ;/. key revert to ; even when shift is pressed. 

I'm not sure what the most elegant way of fixing this is.  I suggest accepting ctl+; as an alternative to ctl+.

Great program !

Peter

**Comment by charlieroberts** [comment]
Hi Peter,

You can remap this as follows:

`Gibber.Environment.CodeMirror.keyMap.gibber[ 'Ctrl-5' ] = Gibber.clear`

Also, If you highlight that code in the Gibber editor and hit Ctrl-P it will preload it before every Gibber session (assuming you're using the same browser) so you won't have to keep typing it in. 

Hope that helps! I'm not sure what the best fix for this is yet either, outside of some type of completely custom key mapping system, but if you have any ideas let me know.

**Comment by jhurlbut** [comment]
I think this has been updated to Gibber.Environment.CodeMirror.keyMap.playground instead of .gibber

**Comment by charlieroberts** [comment]
I think this has now been fixed as best as possible, discussed in https://github.com/gibber-cc/gibber/issues/55
