### ISSUE TITLE
ctrl+ period doesnt seem to clear the scene

### ISSUE THREAD

**Issue by diegodorado** [gibber-cc/gibber#55]
Neither does executing `Clock.stop`
Dont know how to stop gibber, although it sounds great =)

**Comment by charlieroberts** [comment]
old one. `Gibber.clear()` will clear everything. But I also tried to address this by adding `Ctrl+Shift+.` as an alternative shortcut, and added text to the tutorials about this. see 7824d775902546508b766b032a44ff1f0f9544b6 and 1313f027afabc628be1bd3fd705180815d3bf02d
