### ISSUE TITLE
Valid tidal syntax for repeated notes doesn’t work

### ISSUE THREAD

**Issue by khoparzi** [gibber-cc/gibber#57]
Valid tidal syntax like this should work for repeated notes `drums.tidal( '[kd*2, ch*<12 8>, ~ sd]' )`
instead of having to do this
`drums.tidal( '[kd*2, <ch*12 ch*8>, ~ sd]' )`

**Comment by charlieroberts** [comment]
see https://github.com/tidalcycles/strudel/issues/72

**Comment by charlieroberts** [comment]
fixed! thanks to @yaxu for the implementation in strudel and also to @felixroos for helping me troubleshoot this one. d3ec97f32a70b7a7f5126a6e5dc8e6630fe2d093
