### ISSUE TITLE
Tidal division operator doesn't work as expected

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#61]
e.g. 

```
k = Kick()
k.trigger.tidal("[1 0 0 [0 0.5]]/2")
```
Should slow the overall pattern down by 2, but instead seems to change the pattern duration correctly but doesn't shift the events to match.

**Comment by charlieroberts** [comment]
this is a difficult bug to fix but it's on my radar

**Comment by charlieroberts** [comment]
fixed!
