### ISSUE TITLE
forgetting rhythm array causes tab to be unresponsive

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#62]
In gabber (not tested in regular gibber), executing 
s.note.seq( [0,1,2,3] ) //with no rhythm array defined

causes the tab to be unresponsive. Code can still be entered in the codebox but executing has no effect

**Comment by charlieroberts** [comment]
hmmm, so I can run the following in gabber no problem:
```js
s = Synth('bleep')

s.note.seq( [0,1,2,3] )

k = Kick().trigger.seq( 1,1/4 )
```

Is there any more context you can give?

**Comment by charlieroberts** [comment]
ping @ianhattwick
