### ISSUE TITLE
Gabber room code persists

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#63]
Right now there is no way to clear a gabber room; gibber.clear() or ctrl-. do not remove existing code. Upon reentering a room, all existing code is executed.

It would be great if Gibber.clear() or Gabber.clear() refreshed the code on the server.

This is especially problematic if code which causes an error has been executed, as that code will persist and be reexecuted on entering the room.

**Comment by charlieroberts** [comment]
added `Gabber.clear()` in https://github.com/gibber-cc/gibber/commit/ef0d89a87e29d2c16f2a68380d442540d204e4f7
