### ISSUE TITLE
lfo waveforms are not scaled uniformly

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#64]
for the lfo() function, sine and triangle waves are bipolar whereas saw and square waves are unipolar

s = Synth()

s.note.seq([0,1,2,3], 1/4)
s.gain = lfo('sin', btof(1), 0.3, 0.) //twice as fast
s.gain = lfo('sin', btof(1), 0.3, 0.3)
s.gain = lfo('square', btof(1), 0.3, 0.)
s.gain = lfo('saw', btof(1), 0.3, 0.)
s.gain = lfo('triangle', btof(1), 0.3, 0.3) //bipolar as well

**Comment by ianhattwick** [comment]
Also, is there documentation for the available waveforms for lfo() and for 

s.note.seq( sine( btof( 1 ), 7, 0), 1/4) 

style functions?

**Comment by charlieroberts** [comment]
no, there is no documentation, I'll look into that. Hopefully taking everything bipolar will be relatively easy as well.

**Comment by ianhattwick** [comment]
Cool - FYI i think it is only the square wave that is not bipolar (is true for the square() function as well).

**Comment by charlieroberts** [comment]
still no documentation, but all the waves (square, triangle, sine, noise) are correctly biased / scaled now.

**Comment by charlieroberts** [comment]
ok documentation added.

**Comment by charlieroberts** [comment]
I also added documentation for the lfo shorthands `sine`, `square`, `tri`, and `saw`.
