### ISSUE TITLE
use of lfo to control decay times returns samples not seconds

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#65]
Right now a workaround is to wrap scaling parameters in Clock.time() - but it would be better if it were able to parse the output of lfo() as seconds instead of samples

```
s = Synth()
s.note.seq([0,1,2,3], 1/4)
s.decay= lfo('triangle', btof(8), Clock.time( 0.4 ), Clock.time( 0.42) )
```

**Comment by charlieroberts** [comment]
OK, so just to be clear, in:

```js
s = Synth()
s.note.seq([0,1,2,3], 1/4)
s.decay= lfo('triangle', btof(8), Clock.time( 0.4 ), Clock.time( 0.42) )
```

... you'd like to remove the calls to `Clock.time`, right? I think I can make that work... basically when you assign a `gen` object to a time property (attack/decay etc.) gibber would wrap that `gen` object in something that would convert from beats to samples. Does that sound right?

**Comment by ianhattwick** [comment]
Yes, that is correct. Just to make the syntax consistent with other parameters.

-ian

**Comment by charlieroberts** [comment]
Fixed in https://github.com/gibber-cc/gibber/commit/987c4c3e52966bd6c3638b5a7421c5a481935dec
