### ISSUE TITLE
issue pulling latest commit

### ISSUE THREAD

**Issue by jhurlbut** [gibber-cc/gibber#75]
I'm having an issue pulling the latest from the main branch on Windows. The error is:

error: unable to create file playground/resources/tune.json/scalamakesrc2\semisixths_8.js: No such file or directory
error: unable to create file playground/resources/tune.json/scalamakesrc2\smithgw-ball.js: No such file or directory

Seems like it could be a path issue with the forward slashes?

**Comment by jhurlbut** [comment]
was able to get everything working by pulling onto osx and copying over to a windows machine

**Comment by charlieroberts** [comment]
Thanks! This should be fixed in dc72d8d85b216f1bc233530980248544377a7574
