### ISSUE TITLE
Random functions documentation

### ISSUE THREAD

**Issue by charlieroberts** [gibber-cc/gibber#77]
as per [discussion in discord](https://discord.com/channels/790732544491913216/812898570997989426/933205684147871844) none of the various random functions are documented. The old version of gibber had a tutorial that went through this as well, which might be nice to re-create.

**Comment by cpmpercussion** [comment]
confirm would like...

**Comment by charlieroberts** [comment]
in https://github.com/gibber-cc/gibber/commit/68f79fa5770faa7a9c96ed6773a110310e7ca44f and pulled at gibber.cc
