### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Annotations')

### ISSUE THREAD

**Issue by PSW5** [gibber-cc/gibber#80]
When using the following code inside the html
```

verb =  Reverb( 'space' ).bus()
delay = Delay( '1/3' ).bus().connect( verb, .1 )
  

Clock.bpm = 140
 
verb = Reverb( 'space' ).bus() 
lead = Synth( 'cry', { gain:.1, octave:1 })
  .connect( verb, 1 )
  .note.seq( sine( .15, 7 ), [1/2,1,2] )

```
I got this error. How could it be fix? Many Thanks! 
![Screen Shot 2022-04-21 at 2 10 32 PM](https://user-images.githubusercontent.com/49763194/164386631-fa3d447a-8e7f-417e-a4b5-14e1ff73ffb0.png)
t

**Comment by charlieroberts** [comment]
sorry for the delay, but this got fixed at some point :)
