### ISSUE TITLE
Fractal Fun demo throws TypeError: Cannot read properties of undefined (reading '__postprocessing')

### ISSUE THREAD

**Issue by rahji** [gibber-cc/gibber#89]
When trying to execute either of the postprocessing lines at the top of the demo (Blur and Invert) the above error appears in the console. This breaks the demo because the inv variable is used at the bottom and hasn't been defined because of this earlier failure. Tried it in Chrome and Opera on Windows.

The error appears to be coming from:

`      
if (isfx) {
        this.__postprocessing.push(instance.__wrapped);
      }
`

**Comment by charlieroberts** [comment]
Fixed in 1fe283e, thanks!
