### ISSUE TITLE
"8. audiovisual mappings" demo is broken

### ISSUE THREAD

**Issue by rahji** [gibber-cc/gibber#90]
When executing these lines, I get errors in the console and the effect of changing the radius of the sphere does not work:

```
sphere = Sphere().render()
kick = Kick().trigger.seq( 1,1/4 )
sphere.radius = kick
```

First line gives the error: `ReferenceError: sphere is not defined`

Third line says: `ReferenceError: sphere is not defined`

**Comment by charlieroberts** [comment]
fixed in 1fe283e, thanks!
